<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Sharing analyses with ISAnalytics • ISAnalytics</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Sharing analyses with ISAnalytics">
<meta property="og:description" content="ISAnalytics">
<meta property="og:image" content="https://calabrialab.github.io/ISAnalytics/logo.png">
<meta name="robots" content="noindex">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">ISAnalytics</a>
        <span class="version label label-danger" data-toggle="tooltip" data-placement="bottom" title="In-development version">1.3.5</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/aggregate_function_usage.html">Working with aggregate functions</a>
    </li>
    <li>
      <a href="../articles/collision_removal.html">Collision removal functionality</a>
    </li>
    <li>
      <a href="../articles/how_to_import_functions.html">How to use import functions</a>
    </li>
    <li>
      <a href="../articles/report_system.html">ISAnalytics report system</a>
    </li>
    <li>
      <a href="../articles/sharing_analyses.html">Sharing analyses with ISAnalytics</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://calabrialab.github.io/ISAnalytics/">
    <span class="fas fa-code-branch"></span>
     
    RELEASE
  </a>
</li>
<li>
  <a href="https://github.com/calabrialab/ISAnalytics/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="sharing_analyses_files/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="sharing_analyses_files/htmlwidgets-1.5.4/htmlwidgets.js"></script><link href="sharing_analyses_files/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="sharing_analyses_files/datatables-binding-0.19/datatables.js"></script><script src="sharing_analyses_files/jquery-3.6.0/jquery-3.6.0.min.js"></script><link href="sharing_analyses_files/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="sharing_analyses_files/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="sharing_analyses_files/dt-core-1.10.20/js/jquery.dataTables.min.js"></script><link href="sharing_analyses_files/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="sharing_analyses_files/crosstalk-1.1.1/js/crosstalk.min.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Sharing analyses with ISAnalytics</h1>
                        <h4 class="author">Giulia Pais</h4>
            <address class="author_afil">
      <p>San Raffaele Telethon Institute for Gene Therapy - SR-Tiget, Via Olgettina 60, 20132 Milano - Italia</p>
<br><a class="author_email" href="mailto:#"></a><a href="mailto:giuliapais1@gmail.com" class="email">giuliapais1@gmail.com</a>, <a href="mailto:calabria.andrea@hsr.it" class="email">calabria.andrea@hsr.it</a>
      </address>
                  
            <h4 class="date">21 September 2021</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/calabrialab/ISAnalytics/blob/master/vignettes/sharing_analyses.Rmd"><code>vignettes/sharing_analyses.Rmd</code></a></small>
      <div class="hidden name"><code>sharing_analyses.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>In this vignette we explain in more detail how to perform sharing analyses with <em><a href="https://bioconductor.org/packages/3.13/ISAnalytics">ISAnalytics</a></em> and its dedicated sharing functions.</p>
</div>
<div id="installation-and-options" class="section level1">
<h1 class="hasAnchor">
<a href="#installation-and-options" class="anchor"></a>Installation and options</h1>
<p><code>ISAnalytics</code> can be installed quickly in different ways:</p>
<ul>
<li>You can install it via <a href="http://bioconductor.org">Bioconductor</a>
</li>
<li>You can install it via GitHub using the package <code>devtools</code>
</li>
</ul>
<p>There are always 2 versions of the package active:</p>
<ul>
<li>
<code>RELEASE</code> is the latest stable version</li>
<li>
<code>DEVEL</code> is the development version, it is the most up-to-date version where all new features are introduced</li>
</ul>
<div id="installation-from-bioconductor" class="section level2">
<h2 class="hasAnchor">
<a href="#installation-from-bioconductor" class="anchor"></a>Installation from bioconductor</h2>
<p>RELEASE version:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"BiocManager"</span>, quietly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
    <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"BiocManager"</span><span class="op">)</span>
<span class="fu">BiocManager</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/install.html">install</a></span><span class="op">(</span><span class="st">"ISAnalytics"</span><span class="op">)</span></code></pre></div>
<p>DEVEL version:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"BiocManager"</span>, quietly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
    <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"BiocManager"</span><span class="op">)</span>

<span class="co"># The following initializes usage of Bioc devel</span>
<span class="fu">BiocManager</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/install.html">install</a></span><span class="op">(</span>version<span class="op">=</span><span class="st">'devel'</span><span class="op">)</span>

<span class="fu">BiocManager</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/install.html">install</a></span><span class="op">(</span><span class="st">"ISAnalytics"</span><span class="op">)</span></code></pre></div>
</div>
<div id="installation-from-github" class="section level2">
<h2 class="hasAnchor">
<a href="#installation-from-github" class="anchor"></a>Installation from GitHub</h2>
<p>RELEASE:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va">devtools</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
  <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"devtools"</span><span class="op">)</span>
<span class="op">}</span>
<span class="fu">devtools</span><span class="fu">::</span><span class="fu">install_github</span><span class="op">(</span><span class="st">"calabrialab/ISAnalytics"</span>,
                         ref <span class="op">=</span> <span class="st">"RELEASE_3_13"</span>,
                         dependencies <span class="op">=</span> <span class="cn">TRUE</span>,
                         build_vignettes <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>DEVEL:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va">devtools</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
  <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"devtools"</span><span class="op">)</span>
<span class="op">}</span>
<span class="fu">devtools</span><span class="fu">::</span><span class="fu">install_github</span><span class="op">(</span><span class="st">"calabrialab/ISAnalytics"</span>,
                         ref <span class="op">=</span> <span class="st">"master"</span>,
                         dependencies <span class="op">=</span> <span class="cn">TRUE</span>,
                         build_vignettes <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
</div>
<div id="setting-options" class="section level2">
<h2 class="hasAnchor">
<a href="#setting-options" class="anchor"></a>Setting options</h2>
<p><code>ISAnalytics</code> has a verbose option that allows some functions to print additional information to the console while they’re executing. To disable this feature do:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># DISABLE</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span><span class="st">"ISAnalytics.verbose"</span> <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="co"># ENABLE</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span><span class="st">"ISAnalytics.verbose"</span> <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>Some functions also produce report in a user-friendly HTML format, to set this feature:</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># DISABLE HTML REPORTS</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span><span class="st">"ISAnalytics.reports"</span> <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="co"># ENABLE HTML REPORTS</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span><span class="st">"ISAnalytics.reports"</span> <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="shared-integration-sites" class="section level1">
<h1 class="hasAnchor">
<a href="#shared-integration-sites" class="anchor"></a>Shared integration sites</h1>
<p>An integration site is always characterized by a triple of values: <code>(chr, integration_locus, strand)</code>, hence these attributes are always present in integration matrices.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://calabrialab.github.io/ISAnalytics">ISAnalytics</a></span><span class="op">)</span>
<span class="co">#&gt; Loading required package: magrittr</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"integration_matrices"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"association_file"</span><span class="op">)</span></code></pre></div>
<div id="htmlwidget-90b98af36e789ee3a713" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-90b98af36e789ee3a713">{"x":{"filter":"none","vertical":false,"data":[["16","4","5","12","5","12"],[68164148,129390130,84009671,54635693,84009671,54635693],["+","+","-","-","-","-"],["NFATC3","LOC100507487","EDIL3","CBX5","EDIL3","CBX5"],["+","+","-","-","-","-"],["PJ01_POOL01_LTR75LC38_PT001_PT001-103_lenti_GLOBE_PB_1_SLiM_0060_MNC","PJ01_POOL01_LTR53LC32_PT001_PT001-81_lenti_GLOBE_BM_1_SLiM_0180_MNC","PJ01_POOL01_LTR53LC32_PT001_PT001-81_lenti_GLOBE_BM_1_SLiM_0180_MNC","PJ01_POOL01_LTR83LC66_PT001_PT001-81_lenti_GLOBE_BM_1_SLiM_0180_MNC","PJ01_POOL01_LTR83LC66_PT001_PT001-81_lenti_GLOBE_BM_1_SLiM_0180_MNC","PJ01_POOL01_LTR27LC94_PT001_PT001-81_lenti_GLOBE_BM_1_SLiM_0180_MNC"],[182,23219,20205,13269,14748,12588],[102.945718327,68.7374670022,67.1234858245,65.1576001156,61.4698100152,60.8478128336]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>chr<\/th>\n      <th>integration_locus<\/th>\n      <th>strand<\/th>\n      <th>GeneName<\/th>\n      <th>GeneStrand<\/th>\n      <th>CompleteAmplificationID<\/th>\n      <th>seqCount<\/th>\n      <th>fragmentEstimate<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","scrollX":120,"columnDefs":[{"className":"dt-right","targets":[1,6,7]}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script><p>We can aggregate our data in different ways according to our needs (to know more about this topic take a look at the vignette <code><a href="../articles/aggregate_function_usage.html">vignette("aggregate_function_usage", package = "ISAnalytics")</a></code>), obtaining therefore different groups. Each group has an associated set of integration sites.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Aggregation by standard key</span>
<span class="va">agg</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/aggregate_values_by_key.html">aggregate_values_by_key</a></span><span class="op">(</span><span class="va">integration_matrices</span>,
                               <span class="va">association_file</span>,
                               value_cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"seqCount"</span>, <span class="st">"fragmentEstimate"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div id="htmlwidget-567a1598e9e0aef60bd0" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-567a1598e9e0aef60bd0">{"x":{"filter":"none","vertical":false,"data":[["1","1","1","1","1","1"],[8464757,8464757,8607357,8607357,8607357,8607362],["-","-","+","+","+","-"],["RERE","RERE","RERE","RERE","RERE","RERE"],["-","-","-","-","-","-"],["PT001","PT001","PT001","PT001","PT001","PT001"],["MNC","MNC","MNC","MNC","MNC","MNC"],["BM","BM","BM","BM","BM","BM"],["0030","0060","0060","0180","0360","0180"],[542,1,1,1096,330,1702],[3.01147735081,1.00125374215,1.00133972344,5.01068940778,34.1015997274032,4.01318899904]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>chr<\/th>\n      <th>integration_locus<\/th>\n      <th>strand<\/th>\n      <th>GeneName<\/th>\n      <th>GeneStrand<\/th>\n      <th>SubjectID<\/th>\n      <th>CellMarker<\/th>\n      <th>Tissue<\/th>\n      <th>TimePoint<\/th>\n      <th>seqCount_sum<\/th>\n      <th>fragmentEstimate_sum<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","scrollX":120,"columnDefs":[{"className":"dt-right","targets":[1,9,10]}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script><p>An integration site is <em>shared</em> between two or more groups if the same triple is observed in all the groups considered.</p>
</div>
<div id="automated-sharing-counts" class="section level1">
<h1 class="hasAnchor">
<a href="#automated-sharing-counts" class="anchor"></a>Automated sharing counts</h1>
<p>ISAnalytics provides the function <code><a href="../reference/is_sharing.html">is_sharing()</a></code> for computing automated sharing counts. The function has several arguments that can be tuned according to user needs.</p>
<div id="scenario-1-single-input-data-frame-and-single-grouping-key" class="section level2">
<h2 class="hasAnchor">
<a href="#scenario-1-single-input-data-frame-and-single-grouping-key" class="anchor"></a>SCENARIO 1: single input data frame and single grouping key</h2>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sharing_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">agg</span>, 
                        group_key <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, 
                                      <span class="st">"Tissue"</span>, <span class="st">"TimePoint"</span><span class="op">)</span>,
                        n_comp <span class="op">=</span> <span class="fl">2</span>,
                        is_count <span class="op">=</span> <span class="cn">TRUE</span>,
                        relative_is_sharing <span class="op">=</span> <span class="cn">TRUE</span>,
                        minimal <span class="op">=</span> <span class="cn">TRUE</span>,
                        include_self_comp <span class="op">=</span> <span class="cn">FALSE</span>, 
                        keep_genomic_coord <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co">#&gt; Calculating combinations...</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_1</span>
<span class="co">#&gt;                     g1                g2 shared           is_coord count_g1</span>
<span class="co">#&gt;   1: PT001_MNC_BM_0030 PT001_MNC_BM_0060     21 &lt;data.table[21x3]&gt;       54</span>
<span class="co">#&gt;   2: PT001_MNC_BM_0030 PT001_MNC_BM_0180     15 &lt;data.table[15x3]&gt;       54</span>
<span class="co">#&gt;   3: PT001_MNC_BM_0060 PT001_MNC_BM_0180     13 &lt;data.table[13x3]&gt;      114</span>
<span class="co">#&gt;   4: PT001_MNC_BM_0090 PT001_MNC_BM_0180     18 &lt;data.table[18x3]&gt;       59</span>
<span class="co">#&gt;   5: PT001_MNC_BM_0030 PT001_MNC_BM_0360     21 &lt;data.table[21x3]&gt;       54</span>
<span class="co">#&gt;  ---                                                                       </span>
<span class="co">#&gt; 186: PT001_MNC_BM_0090 PT002_MNC_PB_0090      0  &lt;data.table[0x3]&gt;       59</span>
<span class="co">#&gt; 187: PT002_MNC_BM_0060 PT002_MNC_PB_0090      4  &lt;data.table[4x3]&gt;       33</span>
<span class="co">#&gt; 188: PT002_MNC_BM_0090 PT002_MNC_PB_0090      2  &lt;data.table[2x3]&gt;       40</span>
<span class="co">#&gt; 189: PT001_MNC_PB_0090 PT002_MNC_PB_0090      0  &lt;data.table[0x3]&gt;       48</span>
<span class="co">#&gt; 190: PT001_MNC_PB_0360 PT002_MNC_PB_0090      0  &lt;data.table[0x3]&gt;       43</span>
<span class="co">#&gt;      count_g2 count_union    on_g1     on_g2  on_union</span>
<span class="co">#&gt;   1:      114         147 38.88889 18.421053 14.285714</span>
<span class="co">#&gt;   2:       89         128 27.77778 16.853933 11.718750</span>
<span class="co">#&gt;   3:       89         190 11.40351 14.606742  6.842105</span>
<span class="co">#&gt;   4:       89         130 30.50847 20.224719 13.846154</span>
<span class="co">#&gt;   5:       78         111 38.88889 26.923077 18.918919</span>
<span class="co">#&gt;  ---                                                  </span>
<span class="co">#&gt; 186:       24          83  0.00000  0.000000  0.000000</span>
<span class="co">#&gt; 187:       24          53 12.12121 16.666667  7.547170</span>
<span class="co">#&gt; 188:       24          62  5.00000  8.333333  3.225806</span>
<span class="co">#&gt; 189:       24          72  0.00000  0.000000  0.000000</span>
<span class="co">#&gt; 190:       24          67  0.00000  0.000000  0.000000</span></code></pre></div>
<p>In this configuration we set:</p>
<ul>
<li>A single input data frame: <code>agg</code>
</li>
<li>A single grouping key by setting the argument <code>grouping_key</code>. In this specific case, our groups will be identified by a unique combination of <code>SubjectID</code>, <code>CellMarker</code>, <code>Tissue</code> and <code>TimePoint</code>
</li>
<li>
<code>n_comp</code> represents the number of comparisons to compute: 2 means we’re interested in knowing the sharing for PAIRS of distinct groups</li>
<li>We want to keep the counts of distinct integration sites for each group by setting <code>is_count</code> to <code>TRUE</code>
</li>
<li>
<code>relative_is_sharing</code> if set to <code>TRUE</code> adds sharing expressed as a percentage, more precisely it adds a column <code>on_g1</code> that is calculated as the absolute number of shared integrations divided by the cardinality of the first group, <code>on_g2</code> is analogous but is computed on the cardinality of the second group and finally <code>on_union</code> is computed on the cardinality of the union of the two groups.</li>
<li>By setting the argument <code>minimal</code> to <code>TRUE</code> we tell the function to avoid redundant comparisons: in this way only <strong>combinations</strong> and not permutations are included in the output table</li>
<li>
<code>include_self_comp</code> adds rows in the table that are labelled with the same group: these rows always have a 100% sharing with all other groups. There are few scenarios where this is useful, but for now we set it to <code>FALSE</code> since we don’t need it</li>
<li>
<code>keep_genomic_coord</code> allows us to keep the genomic coordinates of the shared integration sites as a separate table</li>
</ul>
<div id="changing-the-number-of-comparisons" class="section level3">
<h3 class="hasAnchor">
<a href="#changing-the-number-of-comparisons" class="anchor"></a>Changing the number of comparisons</h3>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sharing_1_a</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">agg</span>, 
                        group_key <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, 
                                      <span class="st">"Tissue"</span>, <span class="st">"TimePoint"</span><span class="op">)</span>,
                        n_comp <span class="op">=</span> <span class="fl">3</span>,
                        is_count <span class="op">=</span> <span class="cn">TRUE</span>,
                        relative_is_sharing <span class="op">=</span> <span class="cn">TRUE</span>,
                        minimal <span class="op">=</span> <span class="cn">TRUE</span>,
                        include_self_comp <span class="op">=</span> <span class="cn">FALSE</span>, 
                        keep_genomic_coord <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co">#&gt; Calculating combinations...</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_1_a</span>
<span class="co">#&gt;                      g1                g2                g3 shared</span>
<span class="co">#&gt;    1: PT001_MNC_BM_0030 PT001_MNC_BM_0060 PT001_MNC_BM_0180      8</span>
<span class="co">#&gt;    2: PT001_MNC_BM_0030 PT001_MNC_BM_0090 PT001_MNC_BM_0180      9</span>
<span class="co">#&gt;    3: PT001_MNC_BM_0060 PT001_MNC_BM_0090 PT001_MNC_BM_0180      8</span>
<span class="co">#&gt;    4: PT001_MNC_BM_0030 PT001_MNC_BM_0060 PT001_MNC_BM_0360      6</span>
<span class="co">#&gt;    5: PT001_MNC_BM_0030 PT001_MNC_BM_0180 PT001_MNC_BM_0360      9</span>
<span class="co">#&gt;   ---                                                             </span>
<span class="co">#&gt; 1136: PT001_MNC_PB_0060 PT001_MNC_PB_0360 PT002_MNC_PB_0090      0</span>
<span class="co">#&gt; 1137: PT001_MNC_PB_0180 PT001_MNC_PB_0360 PT002_MNC_PB_0090      0</span>
<span class="co">#&gt; 1138: PT001_MNC_PB_0030 PT001_MNC_PB_0360 PT002_MNC_PB_0090      0</span>
<span class="co">#&gt; 1139: PT001_MNC_BM_0090 PT001_MNC_PB_0360 PT002_MNC_PB_0090      0</span>
<span class="co">#&gt; 1140: PT001_MNC_PB_0090 PT001_MNC_PB_0360 PT002_MNC_PB_0090      0</span>
<span class="co">#&gt;                is_coord count_g1 count_g2 count_g3 count_union     on_g1</span>
<span class="co">#&gt;    1: &lt;data.table[8x3]&gt;       54      114       89         216 14.814815</span>
<span class="co">#&gt;    2: &lt;data.table[9x3]&gt;       54       59       89         154 16.666667</span>
<span class="co">#&gt;    3: &lt;data.table[8x3]&gt;      114       59       89         228  7.017544</span>
<span class="co">#&gt;    4: &lt;data.table[6x3]&gt;       54      114       78         198 11.111111</span>
<span class="co">#&gt;    5: &lt;data.table[9x3]&gt;       54       89       78         147 16.666667</span>
<span class="co">#&gt;   ---                                                                   </span>
<span class="co">#&gt; 1136: &lt;data.table[0x3]&gt;       59       43       24         114  0.000000</span>
<span class="co">#&gt; 1137: &lt;data.table[0x3]&gt;       29       43       24          76  0.000000</span>
<span class="co">#&gt; 1138: &lt;data.table[0x3]&gt;       28       43       24          84  0.000000</span>
<span class="co">#&gt; 1139: &lt;data.table[0x3]&gt;       59       43       24         108  0.000000</span>
<span class="co">#&gt; 1140: &lt;data.table[0x3]&gt;       48       43       24          89  0.000000</span>
<span class="co">#&gt;           on_g2     on_g3 on_union</span>
<span class="co">#&gt;    1:  7.017544  8.988764 3.703704</span>
<span class="co">#&gt;    2: 15.254237 10.112360 5.844156</span>
<span class="co">#&gt;    3: 13.559322  8.988764 3.508772</span>
<span class="co">#&gt;    4:  5.263158  7.692308 3.030303</span>
<span class="co">#&gt;    5: 10.112360 11.538462 6.122449</span>
<span class="co">#&gt;   ---                             </span>
<span class="co">#&gt; 1136:  0.000000  0.000000 0.000000</span>
<span class="co">#&gt; 1137:  0.000000  0.000000 0.000000</span>
<span class="co">#&gt; 1138:  0.000000  0.000000 0.000000</span>
<span class="co">#&gt; 1139:  0.000000  0.000000 0.000000</span>
<span class="co">#&gt; 1140:  0.000000  0.000000 0.000000</span></code></pre></div>
<p>Changing the <code>n_comp</code> to 3 means that we want to calculate the sharing between 3 different groups. Note that the <code>shared</code> column contains the counts of integrations that are shared by <strong>ALL</strong> groups, which is equivalent to a set intersection.</p>
<p>Beware of the fact that the more comparisons are requested the more time the computation requires.</p>
</div>
<div id="a-case-when-it-is-useful-to-set-minimal-false" class="section level3">
<h3 class="hasAnchor">
<a href="#a-case-when-it-is-useful-to-set-minimal-false" class="anchor"></a>A case when it is useful to set <code>minimal = FALSE</code>
</h3>
<p>Setting <code>minimal = FALSE</code> produces all possible permutations of the groups and the corresponding values. In combination with <code>include_self_comp = TRUE</code>, this is useful when we want to know the sharing between pairs of groups and plot results as a heatmap.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sharing_1_b</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">agg</span>,
                          group_key <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, 
                                      <span class="st">"Tissue"</span>, <span class="st">"TimePoint"</span><span class="op">)</span>,
                          n_comp <span class="op">=</span> <span class="fl">2</span>,
                          is_count <span class="op">=</span> <span class="cn">TRUE</span>,
                          relative_is_sharing <span class="op">=</span> <span class="cn">TRUE</span>,
                          minimal <span class="op">=</span> <span class="cn">FALSE</span>,
                          include_self_comp <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co">#&gt; Calculating combinations...</span>
<span class="co">#&gt; Calculating self groups (requested)...</span>
<span class="co">#&gt; Calculating permutations (requested)...</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_1_b</span>
<span class="co">#&gt;                     g1                g2 shared count_g1 count_g2 count_union</span>
<span class="co">#&gt;   1: PT001_MNC_BM_0030 PT001_MNC_BM_0030     54       54       54          54</span>
<span class="co">#&gt;   2: PT001_MNC_BM_0030 PT001_MNC_BM_0060     21       54      114         147</span>
<span class="co">#&gt;   3: PT001_MNC_BM_0060 PT001_MNC_BM_0030     21      114       54         147</span>
<span class="co">#&gt;   4: PT001_MNC_BM_0060 PT001_MNC_BM_0060    114      114      114         114</span>
<span class="co">#&gt;   5: PT001_MNC_BM_0030 PT001_MNC_BM_0180     15       54       89         128</span>
<span class="co">#&gt;  ---                                                                         </span>
<span class="co">#&gt; 396: PT001_MNC_PB_0090 PT002_MNC_PB_0090      0       48       24          72</span>
<span class="co">#&gt; 397: PT002_MNC_PB_0090 PT001_MNC_PB_0090      0       24       48          72</span>
<span class="co">#&gt; 398: PT001_MNC_PB_0360 PT002_MNC_PB_0090      0       43       24          67</span>
<span class="co">#&gt; 399: PT002_MNC_PB_0090 PT001_MNC_PB_0360      0       24       43          67</span>
<span class="co">#&gt; 400: PT002_MNC_PB_0090 PT002_MNC_PB_0090     24       24       24          24</span>
<span class="co">#&gt;          on_g1     on_g2  on_union</span>
<span class="co">#&gt;   1: 100.00000 100.00000 100.00000</span>
<span class="co">#&gt;   2:  38.88889  18.42105  14.28571</span>
<span class="co">#&gt;   3:  18.42105  38.88889  14.28571</span>
<span class="co">#&gt;   4: 100.00000 100.00000 100.00000</span>
<span class="co">#&gt;   5:  27.77778  16.85393  11.71875</span>
<span class="co">#&gt;  ---                              </span>
<span class="co">#&gt; 396:   0.00000   0.00000   0.00000</span>
<span class="co">#&gt; 397:   0.00000   0.00000   0.00000</span>
<span class="co">#&gt; 398:   0.00000   0.00000   0.00000</span>
<span class="co">#&gt; 399:   0.00000   0.00000   0.00000</span>
<span class="co">#&gt; 400: 100.00000 100.00000 100.00000</span>
<span class="va">heatmaps</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/sharing_heatmap.html">sharing_heatmap</a></span><span class="op">(</span><span class="va">sharing_1_b</span><span class="op">)</span></code></pre></div>
<p>The function <code><a href="../reference/sharing_heatmap.html">sharing_heatmap()</a></code> automatically plots sharing between 2 groups. There are several arguments to this function that allow us to obtain heatmaps for the absolute sharing values or the relative (percentage) values.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">heatmaps</span><span class="op">$</span><span class="va">absolute</span></code></pre></div>
<p><img src="sharing_analyses_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">heatmaps</span><span class="op">$</span><span class="va">on_g1</span></code></pre></div>
<p><img src="sharing_analyses_files/figure-html/unnamed-chunk-11-2.png" width="700"></p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">heatmaps</span><span class="op">$</span><span class="va">on_union</span></code></pre></div>
<p><img src="sharing_analyses_files/figure-html/unnamed-chunk-11-3.png" width="700"></p>
<p>Beware of the fact that calculating all permutations takes longer than calculating only distinct combinations, therefore if you don’t need your results plotted or you have more than 2 groups to compare you should stick with <code>minimal = TRUE</code> and <code>include_self_comp = FALSE</code>.</p>
</div>
</div>
<div id="scenario-2-single-input-data-frame-and-multiple-grouping-keys" class="section level2">
<h2 class="hasAnchor">
<a href="#scenario-2-single-input-data-frame-and-multiple-grouping-keys" class="anchor"></a>SCENARIO 2: single input data frame and multiple grouping keys</h2>
<p>In the first scenario, groups were homogeneous, that is, they were grouped all with the same key. In this other scenario we want to start with data contained in just one data frame but we want to compare sets of integrations that are grouped differently. To do this we give as input a <strong>list of keys</strong> through the argument <code>group_keys</code>.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sharing_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">agg</span>,
                        group_keys <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
                          g1 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, 
                                 <span class="st">"Tissue"</span>, <span class="st">"TimePoint"</span><span class="op">)</span>,
                          g2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span><span class="op">)</span>,
                          g3 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"CellMarker"</span>, <span class="st">"Tissue"</span><span class="op">)</span>
                          <span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_2</span>
<span class="co">#&gt;                    g1        g2     g3 shared count_g1 count_g2 count_g3</span>
<span class="co">#&gt;  1: PT001_MNC_BM_0030 PT001_MNC MNC_BM     54       54      261      501</span>
<span class="co">#&gt;  2: PT001_MNC_BM_0060 PT001_MNC MNC_BM    114      114      261      501</span>
<span class="co">#&gt;  3: PT001_MNC_BM_0180 PT001_MNC MNC_BM     89       89      261      501</span>
<span class="co">#&gt;  4: PT001_MNC_BM_0360 PT001_MNC MNC_BM     78       78      261      501</span>
<span class="co">#&gt;  5: PT002_MNC_BM_0360 PT001_MNC MNC_BM      2       91      261      501</span>
<span class="co">#&gt;  6: PT001_MNC_PB_0060 PT001_MNC MNC_BM     52       59      261      501</span>
<span class="co">#&gt;  7: PT001_MNC_PB_0180 PT001_MNC MNC_BM     26       29      261      501</span>
<span class="co">#&gt;  8: PT002_MNC_PB_0360 PT001_MNC MNC_BM      3       53      261      501</span>
<span class="co">#&gt;  9: PT002_MNC_PB_0180 PT001_MNC MNC_BM      1       32      261      501</span>
<span class="co">#&gt; 10: PT002_MNC_BM_0030 PT001_MNC MNC_BM      1       98      261      501</span>
<span class="co">#&gt; 11: PT002_MNC_PB_0060 PT001_MNC MNC_BM      0       18      261      501</span>
<span class="co">#&gt; 12: PT002_MNC_PB_0030 PT001_MNC MNC_BM      1       15      261      501</span>
<span class="co">#&gt; 13: PT001_MNC_PB_0030 PT001_MNC MNC_BM     11       28      261      501</span>
<span class="co">#&gt; 14: PT002_MNC_BM_0180 PT001_MNC MNC_BM      1       69      261      501</span>
<span class="co">#&gt; 15: PT001_MNC_BM_0090 PT001_MNC MNC_BM     59       59      261      501</span>
<span class="co">#&gt; 16: PT002_MNC_BM_0060 PT001_MNC MNC_BM      1       33      261      501</span>
<span class="co">#&gt; 17: PT002_MNC_BM_0090 PT001_MNC MNC_BM      0       40      261      501</span>
<span class="co">#&gt; 18: PT001_MNC_PB_0090 PT001_MNC MNC_BM     38       48      261      501</span>
<span class="co">#&gt; 19: PT001_MNC_PB_0360 PT001_MNC MNC_BM     35       43      261      501</span>
<span class="co">#&gt; 20: PT002_MNC_PB_0090 PT001_MNC MNC_BM      0       24      261      501</span>
<span class="co">#&gt; 21: PT001_MNC_BM_0030 PT002_MNC MNC_BM      2       54      316      501</span>
<span class="co">#&gt; 22: PT001_MNC_BM_0060 PT002_MNC MNC_BM      3      114      316      501</span>
<span class="co">#&gt; 23: PT001_MNC_BM_0180 PT002_MNC MNC_BM      3       89      316      501</span>
<span class="co">#&gt; 24: PT001_MNC_BM_0360 PT002_MNC MNC_BM      4       78      316      501</span>
<span class="co">#&gt; 25: PT002_MNC_BM_0360 PT002_MNC MNC_BM     91       91      316      501</span>
<span class="co">#&gt; 26: PT001_MNC_PB_0060 PT002_MNC MNC_BM      3       59      316      501</span>
<span class="co">#&gt; 27: PT001_MNC_PB_0180 PT002_MNC MNC_BM      2       29      316      501</span>
<span class="co">#&gt; 28: PT002_MNC_PB_0360 PT002_MNC MNC_BM      7       53      316      501</span>
<span class="co">#&gt; 29: PT002_MNC_PB_0180 PT002_MNC MNC_BM     26       32      316      501</span>
<span class="co">#&gt; 30: PT002_MNC_BM_0030 PT002_MNC MNC_BM     98       98      316      501</span>
<span class="co">#&gt; 31: PT002_MNC_PB_0060 PT002_MNC MNC_BM     12       18      316      501</span>
<span class="co">#&gt; 32: PT002_MNC_PB_0030 PT002_MNC MNC_BM      9       15      316      501</span>
<span class="co">#&gt; 33: PT001_MNC_PB_0030 PT002_MNC MNC_BM      1       28      316      501</span>
<span class="co">#&gt; 34: PT002_MNC_BM_0180 PT002_MNC MNC_BM     69       69      316      501</span>
<span class="co">#&gt; 35: PT001_MNC_BM_0090 PT002_MNC MNC_BM      2       59      316      501</span>
<span class="co">#&gt; 36: PT002_MNC_BM_0060 PT002_MNC MNC_BM     33       33      316      501</span>
<span class="co">#&gt; 37: PT002_MNC_BM_0090 PT002_MNC MNC_BM     40       40      316      501</span>
<span class="co">#&gt; 38: PT001_MNC_PB_0090 PT002_MNC MNC_BM      3       48      316      501</span>
<span class="co">#&gt; 39: PT001_MNC_PB_0360 PT002_MNC MNC_BM      2       43      316      501</span>
<span class="co">#&gt; 40: PT002_MNC_PB_0090 PT002_MNC MNC_BM     18       24      316      501</span>
<span class="co">#&gt; 41: PT001_MNC_BM_0030 PT001_MNC MNC_PB     27       54      261      227</span>
<span class="co">#&gt; 42: PT001_MNC_BM_0060 PT001_MNC MNC_PB     46      114      261      227</span>
<span class="co">#&gt; 43: PT001_MNC_BM_0180 PT001_MNC MNC_PB     39       89      261      227</span>
<span class="co">#&gt; 44: PT001_MNC_BM_0360 PT001_MNC MNC_PB     41       78      261      227</span>
<span class="co">#&gt; 45: PT002_MNC_BM_0360 PT001_MNC MNC_PB      2       91      261      227</span>
<span class="co">#&gt; 46: PT001_MNC_PB_0060 PT001_MNC MNC_PB     59       59      261      227</span>
<span class="co">#&gt; 47: PT001_MNC_PB_0180 PT001_MNC MNC_PB     29       29      261      227</span>
<span class="co">#&gt; 48: PT002_MNC_PB_0360 PT001_MNC MNC_PB      3       53      261      227</span>
<span class="co">#&gt; 49: PT002_MNC_PB_0180 PT001_MNC MNC_PB      1       32      261      227</span>
<span class="co">#&gt; 50: PT002_MNC_BM_0030 PT001_MNC MNC_PB      1       98      261      227</span>
<span class="co">#&gt; 51: PT002_MNC_PB_0060 PT001_MNC MNC_PB      0       18      261      227</span>
<span class="co">#&gt; 52: PT002_MNC_PB_0030 PT001_MNC MNC_PB      1       15      261      227</span>
<span class="co">#&gt; 53: PT001_MNC_PB_0030 PT001_MNC MNC_PB     28       28      261      227</span>
<span class="co">#&gt; 54: PT002_MNC_BM_0180 PT001_MNC MNC_PB      1       69      261      227</span>
<span class="co">#&gt; 55: PT001_MNC_BM_0090 PT001_MNC MNC_PB     37       59      261      227</span>
<span class="co">#&gt; 56: PT002_MNC_BM_0060 PT001_MNC MNC_PB      1       33      261      227</span>
<span class="co">#&gt; 57: PT002_MNC_BM_0090 PT001_MNC MNC_PB      0       40      261      227</span>
<span class="co">#&gt; 58: PT001_MNC_PB_0090 PT001_MNC MNC_PB     48       48      261      227</span>
<span class="co">#&gt; 59: PT001_MNC_PB_0360 PT001_MNC MNC_PB     43       43      261      227</span>
<span class="co">#&gt; 60: PT002_MNC_PB_0090 PT001_MNC MNC_PB      0       24      261      227</span>
<span class="co">#&gt; 61: PT001_MNC_BM_0030 PT002_MNC MNC_PB      2       54      316      227</span>
<span class="co">#&gt; 62: PT001_MNC_BM_0060 PT002_MNC MNC_PB      3      114      316      227</span>
<span class="co">#&gt; 63: PT001_MNC_BM_0180 PT002_MNC MNC_PB      3       89      316      227</span>
<span class="co">#&gt; 64: PT001_MNC_BM_0360 PT002_MNC MNC_PB      4       78      316      227</span>
<span class="co">#&gt; 65: PT002_MNC_BM_0360 PT002_MNC MNC_PB     10       91      316      227</span>
<span class="co">#&gt; 66: PT001_MNC_PB_0060 PT002_MNC MNC_PB      3       59      316      227</span>
<span class="co">#&gt; 67: PT001_MNC_PB_0180 PT002_MNC MNC_PB      2       29      316      227</span>
<span class="co">#&gt; 68: PT002_MNC_PB_0360 PT002_MNC MNC_PB     53       53      316      227</span>
<span class="co">#&gt; 69: PT002_MNC_PB_0180 PT002_MNC MNC_PB     32       32      316      227</span>
<span class="co">#&gt; 70: PT002_MNC_BM_0030 PT002_MNC MNC_PB     31       98      316      227</span>
<span class="co">#&gt; 71: PT002_MNC_PB_0060 PT002_MNC MNC_PB     18       18      316      227</span>
<span class="co">#&gt; 72: PT002_MNC_PB_0030 PT002_MNC MNC_PB     15       15      316      227</span>
<span class="co">#&gt; 73: PT001_MNC_PB_0030 PT002_MNC MNC_PB      1       28      316      227</span>
<span class="co">#&gt; 74: PT002_MNC_BM_0180 PT002_MNC MNC_PB     26       69      316      227</span>
<span class="co">#&gt; 75: PT001_MNC_BM_0090 PT002_MNC MNC_PB      2       59      316      227</span>
<span class="co">#&gt; 76: PT002_MNC_BM_0060 PT002_MNC MNC_PB     12       33      316      227</span>
<span class="co">#&gt; 77: PT002_MNC_BM_0090 PT002_MNC MNC_PB      7       40      316      227</span>
<span class="co">#&gt; 78: PT001_MNC_PB_0090 PT002_MNC MNC_PB      3       48      316      227</span>
<span class="co">#&gt; 79: PT001_MNC_PB_0360 PT002_MNC MNC_PB      2       43      316      227</span>
<span class="co">#&gt; 80: PT002_MNC_PB_0090 PT002_MNC MNC_PB     24       24      316      227</span>
<span class="co">#&gt;                    g1        g2     g3 shared count_g1 count_g2 count_g3</span>
<span class="co">#&gt;     count_union      on_g1      on_g2      on_g3   on_union</span>
<span class="co">#&gt;  1:         521 100.000000 20.6896552 10.7784431 10.3646833</span>
<span class="co">#&gt;  2:         521 100.000000 43.6781609 22.7544910 21.8809981</span>
<span class="co">#&gt;  3:         521 100.000000 34.0996169 17.7644711 17.0825336</span>
<span class="co">#&gt;  4:         521 100.000000 29.8850575 15.5688623 14.9712092</span>
<span class="co">#&gt;  5:         521   2.197802  0.7662835  0.3992016  0.3838772</span>
<span class="co">#&gt;  6:         521  88.135593 19.9233716 10.3792415  9.9808061</span>
<span class="co">#&gt;  7:         521  89.655172  9.9616858  5.1896208  4.9904031</span>
<span class="co">#&gt;  8:         567   5.660377  1.1494253  0.5988024  0.5291005</span>
<span class="co">#&gt;  9:         527   3.125000  0.3831418  0.1996008  0.1897533</span>
<span class="co">#&gt; 10:         521   1.020408  0.3831418  0.1996008  0.1919386</span>
<span class="co">#&gt; 11:         527   0.000000  0.0000000  0.0000000  0.0000000</span>
<span class="co">#&gt; 12:         527   6.666667  0.3831418  0.1996008  0.1897533</span>
<span class="co">#&gt; 13:         521  39.285714  4.2145594  2.1956088  2.1113244</span>
<span class="co">#&gt; 14:         521   1.449275  0.3831418  0.1996008  0.1919386</span>
<span class="co">#&gt; 15:         521 100.000000 22.6053640 11.7764471 11.3243762</span>
<span class="co">#&gt; 16:         521   3.030303  0.3831418  0.1996008  0.1919386</span>
<span class="co">#&gt; 17:         521   0.000000  0.0000000  0.0000000  0.0000000</span>
<span class="co">#&gt; 18:         521  79.166667 14.5593870  7.5848303  7.2936660</span>
<span class="co">#&gt; 19:         521  81.395349 13.4099617  6.9860279  6.7178503</span>
<span class="co">#&gt; 20:         527   0.000000  0.0000000  0.0000000  0.0000000</span>
<span class="co">#&gt; 21:         547   3.703704  0.6329114  0.3992016  0.3656307</span>
<span class="co">#&gt; 22:         547   2.631579  0.9493671  0.5988024  0.5484461</span>
<span class="co">#&gt; 23:         547   3.370787  0.9493671  0.5988024  0.5484461</span>
<span class="co">#&gt; 24:         547   5.128205  1.2658228  0.7984032  0.7312614</span>
<span class="co">#&gt; 25:         547 100.000000 28.7974684 18.1636727 16.6361974</span>
<span class="co">#&gt; 26:         554   5.084746  0.9493671  0.5988024  0.5415162</span>
<span class="co">#&gt; 27:         550   6.896552  0.6329114  0.3992016  0.3636364</span>
<span class="co">#&gt; 28:         547  13.207547  2.2151899  1.3972056  1.2797075</span>
<span class="co">#&gt; 29:         547  81.250000  8.2278481  5.1896208  4.7531993</span>
<span class="co">#&gt; 30:         547 100.000000 31.0126582 19.5608782 17.9159049</span>
<span class="co">#&gt; 31:         547  66.666667  3.7974684  2.3952096  2.1937843</span>
<span class="co">#&gt; 32:         547  60.000000  2.8481013  1.7964072  1.6453382</span>
<span class="co">#&gt; 33:         564   3.571429  0.3164557  0.1996008  0.1773050</span>
<span class="co">#&gt; 34:         547 100.000000 21.8354430 13.7724551 12.6142596</span>
<span class="co">#&gt; 35:         547   3.389831  0.6329114  0.3992016  0.3656307</span>
<span class="co">#&gt; 36:         547 100.000000 10.4430380  6.5868263  6.0329068</span>
<span class="co">#&gt; 37:         547 100.000000 12.6582278  7.9840319  7.3126143</span>
<span class="co">#&gt; 38:         557   6.250000  0.9493671  0.5988024  0.5385996</span>
<span class="co">#&gt; 39:         555   4.651163  0.6329114  0.3992016  0.3603604</span>
<span class="co">#&gt; 40:         547  75.000000  5.6962025  3.5928144  3.2906764</span>
<span class="co">#&gt; 41:         365  50.000000 10.3448276 11.8942731  7.3972603</span>
<span class="co">#&gt; 42:         365  40.350877 17.6245211 20.2643172 12.6027397</span>
<span class="co">#&gt; 43:         365  43.820225 14.9425287 17.1806167 10.6849315</span>
<span class="co">#&gt; 44:         365  52.564103 15.7088123 18.0616740 11.2328767</span>
<span class="co">#&gt; 45:         446   2.197802  0.7662835  0.8810573  0.4484305</span>
<span class="co">#&gt; 46:         365 100.000000 22.6053640 25.9911894 16.1643836</span>
<span class="co">#&gt; 47:         365 100.000000 11.1111111 12.7753304  7.9452055</span>
<span class="co">#&gt; 48:         365   5.660377  1.1494253  1.3215859  0.8219178</span>
<span class="co">#&gt; 49:         365   3.125000  0.3831418  0.4405286  0.2739726</span>
<span class="co">#&gt; 50:         432   1.020408  0.3831418  0.4405286  0.2314815</span>
<span class="co">#&gt; 51:         365   0.000000  0.0000000  0.0000000  0.0000000</span>
<span class="co">#&gt; 52:         365   6.666667  0.3831418  0.4405286  0.2739726</span>
<span class="co">#&gt; 53:         365 100.000000 10.7279693 12.3348018  7.6712329</span>
<span class="co">#&gt; 54:         408   1.449275  0.3831418  0.4405286  0.2450980</span>
<span class="co">#&gt; 55:         365  62.711864 14.1762452 16.2995595 10.1369863</span>
<span class="co">#&gt; 56:         386   3.030303  0.3831418  0.4405286  0.2590674</span>
<span class="co">#&gt; 57:         398   0.000000  0.0000000  0.0000000  0.0000000</span>
<span class="co">#&gt; 58:         365 100.000000 18.3908046 21.1453744 13.1506849</span>
<span class="co">#&gt; 59:         365 100.000000 16.4750958 18.9427313 11.7808219</span>
<span class="co">#&gt; 60:         365   0.000000  0.0000000  0.0000000  0.0000000</span>
<span class="co">#&gt; 61:         456   3.703704  0.6329114  0.8810573  0.4385965</span>
<span class="co">#&gt; 62:         497   2.631579  0.9493671  1.3215859  0.6036217</span>
<span class="co">#&gt; 63:         479   3.370787  0.9493671  1.3215859  0.6263048</span>
<span class="co">#&gt; 64:         466   5.128205  1.2658228  1.7621145  0.8583691</span>
<span class="co">#&gt; 65:         429  10.989011  3.1645570  4.4052863  2.3310023</span>
<span class="co">#&gt; 66:         429   5.084746  0.9493671  1.3215859  0.6993007</span>
<span class="co">#&gt; 67:         429   6.896552  0.6329114  0.8810573  0.4662005</span>
<span class="co">#&gt; 68:         429 100.000000 16.7721519 23.3480176 12.3543124</span>
<span class="co">#&gt; 69:         429 100.000000 10.1265823 14.0969163  7.4592075</span>
<span class="co">#&gt; 70:         429  31.632653  9.8101266 13.6563877  7.2261072</span>
<span class="co">#&gt; 71:         429 100.000000  5.6962025  7.9295154  4.1958042</span>
<span class="co">#&gt; 72:         429 100.000000  4.7468354  6.6079295  3.4965035</span>
<span class="co">#&gt; 73:         429   3.571429  0.3164557  0.4405286  0.2331002</span>
<span class="co">#&gt; 74:         429  37.681159  8.2278481 11.4537445  6.0606061</span>
<span class="co">#&gt; 75:         451   3.389831  0.6329114  0.8810573  0.4434590</span>
<span class="co">#&gt; 76:         429  36.363636  3.7974684  5.2863436  2.7972028</span>
<span class="co">#&gt; 77:         429  17.500000  2.2151899  3.0837004  1.6317016</span>
<span class="co">#&gt; 78:         429   6.250000  0.9493671  1.3215859  0.6993007</span>
<span class="co">#&gt; 79:         429   4.651163  0.6329114  0.8810573  0.4662005</span>
<span class="co">#&gt; 80:         429 100.000000  7.5949367 10.5726872  5.5944056</span>
<span class="co">#&gt;     count_union      on_g1      on_g2      on_g3   on_union</span></code></pre></div>
<p>There are a few things to keep in mind in this case:</p>
<ul>
<li>The arguments <code>group_key</code> (notice the absence of plural), <code>n_comp</code> and <code>include_self_comp</code> are ignored: the number of comparisons is automatically detected by counting the provided keys and a self comparison doesn’t make sense since group labels are different</li>
<li>If you provide a list of identical keys or just one key you fall back to scenario 1</li>
</ul>
</div>
<div id="scenario-3-multiple-input-data-frame-and-single-grouping-key" class="section level2">
<h2 class="hasAnchor">
<a href="#scenario-3-multiple-input-data-frame-and-single-grouping-key" class="anchor"></a>SCENARIO 3: multiple input data frame and single grouping key</h2>
<p>Providing multiple input data frames and the same grouping key is an effective way to reduce the number of comparisons performed. Let’s make an example: suppose we’re interested in comparing groups labelled by a unique combination of <code>SubjectID</code>, <code>CellMarker</code>, <code>Tissue</code> and <code>TimePoint</code>, but this time we want the first group to contain only integrations relative to <code>PT001_MNC_BM_0030</code> and the second group to contain only integrations relative to <code>PT001_MNC_BM_0060</code>.</p>
<p>We’re going to filter the original data frame in order to obtain only relevant data in 2 separated tables and then proceed by calling the function.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">first_sample</span> <span class="op">&lt;-</span> <span class="va">agg</span> <span class="op">%&gt;%</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">SubjectID</span> <span class="op">==</span> <span class="st">"PT001"</span>, <span class="va">CellMarker</span> <span class="op">==</span> <span class="st">"MNC"</span>, <span class="va">Tissue</span> <span class="op">==</span> <span class="st">"BM"</span>, 
         <span class="va">TimePoint</span> <span class="op">==</span> <span class="st">"0030"</span><span class="op">)</span>
<span class="va">second_sample</span> <span class="op">&lt;-</span> <span class="va">agg</span> <span class="op">%&gt;%</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">SubjectID</span> <span class="op">==</span> <span class="st">"PT001"</span>, <span class="va">CellMarker</span> <span class="op">==</span> <span class="st">"MNC"</span>, <span class="va">Tissue</span> <span class="op">==</span> <span class="st">"BM"</span>, 
         <span class="va">TimePoint</span> <span class="op">==</span> <span class="st">"0060"</span><span class="op">)</span>
<span class="va">sharing_3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">first_sample</span>, <span class="va">second_sample</span>,
                        group_key <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, 
                                      <span class="st">"Tissue"</span>, <span class="st">"TimePoint"</span><span class="op">)</span>,
                        is_count <span class="op">=</span> <span class="cn">TRUE</span>,
                        relative_is_sharing <span class="op">=</span> <span class="cn">TRUE</span>,
                        minimal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_3</span>
<span class="co">#&gt;                   g1                g2 shared count_g1 count_g2 count_union</span>
<span class="co">#&gt; 1: PT001_MNC_BM_0030 PT001_MNC_BM_0060     21       54      114         147</span>
<span class="co">#&gt;       on_g1    on_g2 on_union</span>
<span class="co">#&gt; 1: 38.88889 18.42105 14.28571</span></code></pre></div>
<p>Once again the arguments <code>n_comp</code> and <code>include_self_comp</code> are ignored: the number of comparisons is equal to the number of data frames in input.</p>
</div>
<div id="scenario-4-multiple-input-data-frame-and-multiple-grouping-keys" class="section level2">
<h2 class="hasAnchor">
<a href="#scenario-4-multiple-input-data-frame-and-multiple-grouping-keys" class="anchor"></a>SCENARIO 4: multiple input data frame and multiple grouping keys</h2>
<p>Finally, the most general scenario is when we have multiple data frames with multiple keys. In this case the number of data frames must be equal to the number of provided keys and grouping keys are applied in order ( data frame 1 is grouped with key 1, data frame 2 is grouped with key 2, and so on).</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df1</span> <span class="op">&lt;-</span> <span class="va">agg</span> <span class="op">%&gt;%</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">TimePoint</span> <span class="op">==</span> <span class="st">"0030"</span><span class="op">)</span>
<span class="va">df2</span> <span class="op">&lt;-</span> <span class="va">agg</span> <span class="op">%&gt;%</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">TimePoint</span> <span class="op">==</span> <span class="st">"0060"</span><span class="op">)</span>
<span class="va">df3</span> <span class="op">&lt;-</span> <span class="va">agg</span> <span class="op">%&gt;%</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">TimePoint</span> <span class="op">==</span> <span class="st">"0180"</span><span class="op">)</span>

<span class="va">keys</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>g1 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, <span class="st">"Tissue"</span><span class="op">)</span>,
             g2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"Tissue"</span><span class="op">)</span>,
             g3 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, <span class="st">"Tissue"</span><span class="op">)</span><span class="op">)</span>

<span class="va">sharing_4</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">df1</span>, <span class="va">df2</span>, <span class="va">df3</span>, group_keys <span class="op">=</span> <span class="va">keys</span><span class="op">)</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_4</span>
<span class="co">#&gt;               g1       g2           g3 shared count_g1 count_g2 count_g3</span>
<span class="co">#&gt;  1: PT001_MNC_BM PT001_BM PT001_MNC_BM      8       54      114       89</span>
<span class="co">#&gt;  2: PT002_MNC_BM PT001_BM PT001_MNC_BM      0       98      114       89</span>
<span class="co">#&gt;  3: PT002_MNC_PB PT001_BM PT001_MNC_BM      0       15      114       89</span>
<span class="co">#&gt;  4: PT001_MNC_PB PT001_BM PT001_MNC_BM      0       28      114       89</span>
<span class="co">#&gt;  5: PT001_MNC_BM PT001_PB PT001_MNC_BM      8       54       59       89</span>
<span class="co">#&gt;  6: PT002_MNC_BM PT001_PB PT001_MNC_BM      0       98       59       89</span>
<span class="co">#&gt;  7: PT002_MNC_PB PT001_PB PT001_MNC_BM      0       15       59       89</span>
<span class="co">#&gt;  8: PT001_MNC_PB PT001_PB PT001_MNC_BM      0       28       59       89</span>
<span class="co">#&gt;  9: PT001_MNC_BM PT002_PB PT001_MNC_BM      0       54       18       89</span>
<span class="co">#&gt; 10: PT002_MNC_BM PT002_PB PT001_MNC_BM      0       98       18       89</span>
<span class="co">#&gt; 11: PT002_MNC_PB PT002_PB PT001_MNC_BM      0       15       18       89</span>
<span class="co">#&gt; 12: PT001_MNC_PB PT002_PB PT001_MNC_BM      0       28       18       89</span>
<span class="co">#&gt; 13: PT001_MNC_BM PT002_BM PT001_MNC_BM      0       54       33       89</span>
<span class="co">#&gt; 14: PT002_MNC_BM PT002_BM PT001_MNC_BM      0       98       33       89</span>
<span class="co">#&gt; 15: PT002_MNC_PB PT002_BM PT001_MNC_BM      0       15       33       89</span>
<span class="co">#&gt; 16: PT001_MNC_PB PT002_BM PT001_MNC_BM      0       28       33       89</span>
<span class="co">#&gt; 17: PT001_MNC_BM PT001_BM PT001_MNC_PB      0       54      114       29</span>
<span class="co">#&gt; 18: PT002_MNC_BM PT001_BM PT001_MNC_PB      0       98      114       29</span>
<span class="co">#&gt; 19: PT002_MNC_PB PT001_BM PT001_MNC_PB      0       15      114       29</span>
<span class="co">#&gt; 20: PT001_MNC_PB PT001_BM PT001_MNC_PB      0       28      114       29</span>
<span class="co">#&gt; 21: PT001_MNC_BM PT001_PB PT001_MNC_PB      0       54       59       29</span>
<span class="co">#&gt; 22: PT002_MNC_BM PT001_PB PT001_MNC_PB      0       98       59       29</span>
<span class="co">#&gt; 23: PT002_MNC_PB PT001_PB PT001_MNC_PB      0       15       59       29</span>
<span class="co">#&gt; 24: PT001_MNC_PB PT001_PB PT001_MNC_PB      0       28       59       29</span>
<span class="co">#&gt; 25: PT001_MNC_BM PT002_PB PT001_MNC_PB      0       54       18       29</span>
<span class="co">#&gt; 26: PT002_MNC_BM PT002_PB PT001_MNC_PB      0       98       18       29</span>
<span class="co">#&gt; 27: PT002_MNC_PB PT002_PB PT001_MNC_PB      0       15       18       29</span>
<span class="co">#&gt; 28: PT001_MNC_PB PT002_PB PT001_MNC_PB      0       28       18       29</span>
<span class="co">#&gt; 29: PT001_MNC_BM PT002_BM PT001_MNC_PB      0       54       33       29</span>
<span class="co">#&gt; 30: PT002_MNC_BM PT002_BM PT001_MNC_PB      0       98       33       29</span>
<span class="co">#&gt; 31: PT002_MNC_PB PT002_BM PT001_MNC_PB      0       15       33       29</span>
<span class="co">#&gt; 32: PT001_MNC_PB PT002_BM PT001_MNC_PB      0       28       33       29</span>
<span class="co">#&gt; 33: PT001_MNC_BM PT001_BM PT002_MNC_PB      0       54      114       32</span>
<span class="co">#&gt; 34: PT002_MNC_BM PT001_BM PT002_MNC_PB      0       98      114       32</span>
<span class="co">#&gt; 35: PT002_MNC_PB PT001_BM PT002_MNC_PB      0       15      114       32</span>
<span class="co">#&gt; 36: PT001_MNC_PB PT001_BM PT002_MNC_PB      0       28      114       32</span>
<span class="co">#&gt; 37: PT001_MNC_BM PT001_PB PT002_MNC_PB      0       54       59       32</span>
<span class="co">#&gt; 38: PT002_MNC_BM PT001_PB PT002_MNC_PB      0       98       59       32</span>
<span class="co">#&gt; 39: PT002_MNC_PB PT001_PB PT002_MNC_PB      0       15       59       32</span>
<span class="co">#&gt; 40: PT001_MNC_PB PT001_PB PT002_MNC_PB      0       28       59       32</span>
<span class="co">#&gt; 41: PT001_MNC_BM PT002_PB PT002_MNC_PB      0       54       18       32</span>
<span class="co">#&gt; 42: PT002_MNC_BM PT002_PB PT002_MNC_PB      0       98       18       32</span>
<span class="co">#&gt; 43: PT002_MNC_PB PT002_PB PT002_MNC_PB      6       15       18       32</span>
<span class="co">#&gt; 44: PT001_MNC_PB PT002_PB PT002_MNC_PB      0       28       18       32</span>
<span class="co">#&gt; 45: PT001_MNC_BM PT002_BM PT002_MNC_PB      0       54       33       32</span>
<span class="co">#&gt; 46: PT002_MNC_BM PT002_BM PT002_MNC_PB      0       98       33       32</span>
<span class="co">#&gt; 47: PT002_MNC_PB PT002_BM PT002_MNC_PB      0       15       33       32</span>
<span class="co">#&gt; 48: PT001_MNC_PB PT002_BM PT002_MNC_PB      0       28       33       32</span>
<span class="co">#&gt; 49: PT001_MNC_BM PT001_BM PT002_MNC_BM      0       54      114       69</span>
<span class="co">#&gt; 50: PT002_MNC_BM PT001_BM PT002_MNC_BM      0       98      114       69</span>
<span class="co">#&gt; 51: PT002_MNC_PB PT001_BM PT002_MNC_BM      0       15      114       69</span>
<span class="co">#&gt; 52: PT001_MNC_PB PT001_BM PT002_MNC_BM      0       28      114       69</span>
<span class="co">#&gt; 53: PT001_MNC_BM PT001_PB PT002_MNC_BM      0       54       59       69</span>
<span class="co">#&gt; 54: PT002_MNC_BM PT001_PB PT002_MNC_BM      0       98       59       69</span>
<span class="co">#&gt; 55: PT002_MNC_PB PT001_PB PT002_MNC_BM      0       15       59       69</span>
<span class="co">#&gt; 56: PT001_MNC_PB PT001_PB PT002_MNC_BM      0       28       59       69</span>
<span class="co">#&gt; 57: PT001_MNC_BM PT002_PB PT002_MNC_BM      0       54       18       69</span>
<span class="co">#&gt; 58: PT002_MNC_BM PT002_PB PT002_MNC_BM      3       98       18       69</span>
<span class="co">#&gt; 59: PT002_MNC_PB PT002_PB PT002_MNC_BM      0       15       18       69</span>
<span class="co">#&gt; 60: PT001_MNC_PB PT002_PB PT002_MNC_BM      0       28       18       69</span>
<span class="co">#&gt; 61: PT001_MNC_BM PT002_BM PT002_MNC_BM      0       54       33       69</span>
<span class="co">#&gt; 62: PT002_MNC_BM PT002_BM PT002_MNC_BM      3       98       33       69</span>
<span class="co">#&gt; 63: PT002_MNC_PB PT002_BM PT002_MNC_BM      0       15       33       69</span>
<span class="co">#&gt; 64: PT001_MNC_PB PT002_BM PT002_MNC_BM      0       28       33       69</span>
<span class="co">#&gt;               g1       g2           g3 shared count_g1 count_g2 count_g3</span>
<span class="co">#&gt;     count_union     on_g1     on_g2     on_g3  on_union</span>
<span class="co">#&gt;  1:         216 14.814815  7.017544  8.988764  3.703704</span>
<span class="co">#&gt;  2:         370  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;  3:         255  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;  4:         240  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;  5:         160 14.814815 13.559322  8.988764  5.000000</span>
<span class="co">#&gt;  6:         314  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;  7:         201  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;  8:         188  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;  9:         146  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 10:         291  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 11:         180  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 12:         189  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 13:         160  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 14:         299  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 15:         196  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 16:         203  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 17:         240  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 18:         297  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 19:         183  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 20:         144  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 21:         188  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 22:         248  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 23:         135  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 24:          95  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 25:         189  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 26:         219  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 27:         108  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 28:          75  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 29:         203  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 30:         228  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 31:         125  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 32:          90  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 33:         255  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 34:         279  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 35:         153  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 36:         183  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 37:         201  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 38:         226  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 39:         100  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 40:         135  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 41:         180  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 42:         170  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 43:          52 40.000000 33.333333 18.750000 11.538462</span>
<span class="co">#&gt; 44:         108  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 45:         196  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 46:         184  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 47:          69  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 48:         125  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 49:         370  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 50:         268  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 51:         279  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 52:         297  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 53:         314  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 54:         213  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 55:         226  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 56:         248  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 57:         291  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 58:         163  3.061224 16.666667  4.347826  1.840491</span>
<span class="co">#&gt; 59:         170  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 60:         219  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 61:         299  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 62:         172  3.061224  9.090909  4.347826  1.744186</span>
<span class="co">#&gt; 63:         184  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt; 64:         228  0.000000  0.000000  0.000000  0.000000</span>
<span class="co">#&gt;     count_union     on_g1     on_g2     on_g3  on_union</span></code></pre></div>
<p>Notice that in this example the keys for g1 and g3 are the same, meaning the labels of the groups are actually the same, however you should remember that the groups contain a <strong>different set of integration sites</strong> since they come from different data frames.</p>
</div>
</div>
<div id="plotting-sharing-results" class="section level1">
<h1 class="hasAnchor">
<a href="#plotting-sharing-results" class="anchor"></a>Plotting sharing results</h1>
<p>When we have more than 2 comparisons it is convenient to plot them as venn or euler diagrams. ISAnalytics has a fast way to do that through the functions <code><a href="../reference/is_sharing.html">is_sharing()</a></code> and <code><a href="../reference/sharing_venn.html">sharing_venn()</a></code>.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sharing_5</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/is_sharing.html">is_sharing</a></span><span class="op">(</span><span class="va">agg</span>,
                        group_keys <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
                          g1 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span>, 
                                 <span class="st">"Tissue"</span>, <span class="st">"TimePoint"</span><span class="op">)</span>,
                          g2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"SubjectID"</span>, <span class="st">"CellMarker"</span><span class="op">)</span>,
                          g3 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"CellMarker"</span>, <span class="st">"Tissue"</span><span class="op">)</span>
                          <span class="op">)</span>, table_for_venn <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co">#&gt; Done!</span>
<span class="va">sharing_5</span>
<span class="co">#&gt;                    g1        g2     g3 shared count_g1 count_g2 count_g3</span>
<span class="co">#&gt;  1: PT001_MNC_BM_0030 PT001_MNC MNC_BM     54       54      261      501</span>
<span class="co">#&gt;  2: PT001_MNC_BM_0060 PT001_MNC MNC_BM    114      114      261      501</span>
<span class="co">#&gt;  3: PT001_MNC_BM_0180 PT001_MNC MNC_BM     89       89      261      501</span>
<span class="co">#&gt;  4: PT001_MNC_BM_0360 PT001_MNC MNC_BM     78       78      261      501</span>
<span class="co">#&gt;  5: PT002_MNC_BM_0360 PT001_MNC MNC_BM      2       91      261      501</span>
<span class="co">#&gt;  6: PT001_MNC_PB_0060 PT001_MNC MNC_BM     52       59      261      501</span>
<span class="co">#&gt;  7: PT001_MNC_PB_0180 PT001_MNC MNC_BM     26       29      261      501</span>
<span class="co">#&gt;  8: PT002_MNC_PB_0360 PT001_MNC MNC_BM      3       53      261      501</span>
<span class="co">#&gt;  9: PT002_MNC_PB_0180 PT001_MNC MNC_BM      1       32      261      501</span>
<span class="co">#&gt; 10: PT002_MNC_BM_0030 PT001_MNC MNC_BM      1       98      261      501</span>
<span class="co">#&gt; 11: PT002_MNC_PB_0060 PT001_MNC MNC_BM      0       18      261      501</span>
<span class="co">#&gt; 12: PT002_MNC_PB_0030 PT001_MNC MNC_BM      1       15      261      501</span>
<span class="co">#&gt; 13: PT001_MNC_PB_0030 PT001_MNC MNC_BM     11       28      261      501</span>
<span class="co">#&gt; 14: PT002_MNC_BM_0180 PT001_MNC MNC_BM      1       69      261      501</span>
<span class="co">#&gt; 15: PT001_MNC_BM_0090 PT001_MNC MNC_BM     59       59      261      501</span>
<span class="co">#&gt; 16: PT002_MNC_BM_0060 PT001_MNC MNC_BM      1       33      261      501</span>
<span class="co">#&gt; 17: PT002_MNC_BM_0090 PT001_MNC MNC_BM      0       40      261      501</span>
<span class="co">#&gt; 18: PT001_MNC_PB_0090 PT001_MNC MNC_BM     38       48      261      501</span>
<span class="co">#&gt; 19: PT001_MNC_PB_0360 PT001_MNC MNC_BM     35       43      261      501</span>
<span class="co">#&gt; 20: PT002_MNC_PB_0090 PT001_MNC MNC_BM      0       24      261      501</span>
<span class="co">#&gt; 21: PT001_MNC_BM_0030 PT002_MNC MNC_BM      2       54      316      501</span>
<span class="co">#&gt; 22: PT001_MNC_BM_0060 PT002_MNC MNC_BM      3      114      316      501</span>
<span class="co">#&gt; 23: PT001_MNC_BM_0180 PT002_MNC MNC_BM      3       89      316      501</span>
<span class="co">#&gt; 24: PT001_MNC_BM_0360 PT002_MNC MNC_BM      4       78      316      501</span>
<span class="co">#&gt; 25: PT002_MNC_BM_0360 PT002_MNC MNC_BM     91       91      316      501</span>
<span class="co">#&gt; 26: PT001_MNC_PB_0060 PT002_MNC MNC_BM      3       59      316      501</span>
<span class="co">#&gt; 27: PT001_MNC_PB_0180 PT002_MNC MNC_BM      2       29      316      501</span>
<span class="co">#&gt; 28: PT002_MNC_PB_0360 PT002_MNC MNC_BM      7       53      316      501</span>
<span class="co">#&gt; 29: PT002_MNC_PB_0180 PT002_MNC MNC_BM     26       32      316      501</span>
<span class="co">#&gt; 30: PT002_MNC_BM_0030 PT002_MNC MNC_BM     98       98      316      501</span>
<span class="co">#&gt; 31: PT002_MNC_PB_0060 PT002_MNC MNC_BM     12       18      316      501</span>
<span class="co">#&gt; 32: PT002_MNC_PB_0030 PT002_MNC MNC_BM      9       15      316      501</span>
<span class="co">#&gt; 33: PT001_MNC_PB_0030 PT002_MNC MNC_BM      1       28      316      501</span>
<span class="co">#&gt; 34: PT002_MNC_BM_0180 PT002_MNC MNC_BM     69       69      316      501</span>
<span class="co">#&gt; 35: PT001_MNC_BM_0090 PT002_MNC MNC_BM      2       59      316      501</span>
<span class="co">#&gt; 36: PT002_MNC_BM_0060 PT002_MNC MNC_BM     33       33      316      501</span>
<span class="co">#&gt; 37: PT002_MNC_BM_0090 PT002_MNC MNC_BM     40       40      316      501</span>
<span class="co">#&gt; 38: PT001_MNC_PB_0090 PT002_MNC MNC_BM      3       48      316      501</span>
<span class="co">#&gt; 39: PT001_MNC_PB_0360 PT002_MNC MNC_BM      2       43      316      501</span>
<span class="co">#&gt; 40: PT002_MNC_PB_0090 PT002_MNC MNC_BM     18       24      316      501</span>
<span class="co">#&gt; 41: PT001_MNC_BM_0030 PT001_MNC MNC_PB     27       54      261      227</span>
<span class="co">#&gt; 42: PT001_MNC_BM_0060 PT001_MNC MNC_PB     46      114      261      227</span>
<span class="co">#&gt; 43: PT001_MNC_BM_0180 PT001_MNC MNC_PB     39       89      261      227</span>
<span class="co">#&gt; 44: PT001_MNC_BM_0360 PT001_MNC MNC_PB     41       78      261      227</span>
<span class="co">#&gt; 45: PT002_MNC_BM_0360 PT001_MNC MNC_PB      2       91      261      227</span>
<span class="co">#&gt; 46: PT001_MNC_PB_0060 PT001_MNC MNC_PB     59       59      261      227</span>
<span class="co">#&gt; 47: PT001_MNC_PB_0180 PT001_MNC MNC_PB     29       29      261      227</span>
<span class="co">#&gt; 48: PT002_MNC_PB_0360 PT001_MNC MNC_PB      3       53      261      227</span>
<span class="co">#&gt; 49: PT002_MNC_PB_0180 PT001_MNC MNC_PB      1       32      261      227</span>
<span class="co">#&gt; 50: PT002_MNC_BM_0030 PT001_MNC MNC_PB      1       98      261      227</span>
<span class="co">#&gt; 51: PT002_MNC_PB_0060 PT001_MNC MNC_PB      0       18      261      227</span>
<span class="co">#&gt; 52: PT002_MNC_PB_0030 PT001_MNC MNC_PB      1       15      261      227</span>
<span class="co">#&gt; 53: PT001_MNC_PB_0030 PT001_MNC MNC_PB     28       28      261      227</span>
<span class="co">#&gt; 54: PT002_MNC_BM_0180 PT001_MNC MNC_PB      1       69      261      227</span>
<span class="co">#&gt; 55: PT001_MNC_BM_0090 PT001_MNC MNC_PB     37       59      261      227</span>
<span class="co">#&gt; 56: PT002_MNC_BM_0060 PT001_MNC MNC_PB      1       33      261      227</span>
<span class="co">#&gt; 57: PT002_MNC_BM_0090 PT001_MNC MNC_PB      0       40      261      227</span>
<span class="co">#&gt; 58: PT001_MNC_PB_0090 PT001_MNC MNC_PB     48       48      261      227</span>
<span class="co">#&gt; 59: PT001_MNC_PB_0360 PT001_MNC MNC_PB     43       43      261      227</span>
<span class="co">#&gt; 60: PT002_MNC_PB_0090 PT001_MNC MNC_PB      0       24      261      227</span>
<span class="co">#&gt; 61: PT001_MNC_BM_0030 PT002_MNC MNC_PB      2       54      316      227</span>
<span class="co">#&gt; 62: PT001_MNC_BM_0060 PT002_MNC MNC_PB      3      114      316      227</span>
<span class="co">#&gt; 63: PT001_MNC_BM_0180 PT002_MNC MNC_PB      3       89      316      227</span>
<span class="co">#&gt; 64: PT001_MNC_BM_0360 PT002_MNC MNC_PB      4       78      316      227</span>
<span class="co">#&gt; 65: PT002_MNC_BM_0360 PT002_MNC MNC_PB     10       91      316      227</span>
<span class="co">#&gt; 66: PT001_MNC_PB_0060 PT002_MNC MNC_PB      3       59      316      227</span>
<span class="co">#&gt; 67: PT001_MNC_PB_0180 PT002_MNC MNC_PB      2       29      316      227</span>
<span class="co">#&gt; 68: PT002_MNC_PB_0360 PT002_MNC MNC_PB     53       53      316      227</span>
<span class="co">#&gt; 69: PT002_MNC_PB_0180 PT002_MNC MNC_PB     32       32      316      227</span>
<span class="co">#&gt; 70: PT002_MNC_BM_0030 PT002_MNC MNC_PB     31       98      316      227</span>
<span class="co">#&gt; 71: PT002_MNC_PB_0060 PT002_MNC MNC_PB     18       18      316      227</span>
<span class="co">#&gt; 72: PT002_MNC_PB_0030 PT002_MNC MNC_PB     15       15      316      227</span>
<span class="co">#&gt; 73: PT001_MNC_PB_0030 PT002_MNC MNC_PB      1       28      316      227</span>
<span class="co">#&gt; 74: PT002_MNC_BM_0180 PT002_MNC MNC_PB     26       69      316      227</span>
<span class="co">#&gt; 75: PT001_MNC_BM_0090 PT002_MNC MNC_PB      2       59      316      227</span>
<span class="co">#&gt; 76: PT002_MNC_BM_0060 PT002_MNC MNC_PB     12       33      316      227</span>
<span class="co">#&gt; 77: PT002_MNC_BM_0090 PT002_MNC MNC_PB      7       40      316      227</span>
<span class="co">#&gt; 78: PT001_MNC_PB_0090 PT002_MNC MNC_PB      3       48      316      227</span>
<span class="co">#&gt; 79: PT001_MNC_PB_0360 PT002_MNC MNC_PB      2       43      316      227</span>
<span class="co">#&gt; 80: PT002_MNC_PB_0090 PT002_MNC MNC_PB     24       24      316      227</span>
<span class="co">#&gt;                    g1        g2     g3 shared count_g1 count_g2 count_g3</span>
<span class="co">#&gt;     count_union      on_g1      on_g2      on_g3   on_union      truth_tbl_venn</span>
<span class="co">#&gt;  1:         521 100.000000 20.6896552 10.7784431 10.3646833 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  2:         521 100.000000 43.6781609 22.7544910 21.8809981 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  3:         521 100.000000 34.0996169 17.7644711 17.0825336 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  4:         521 100.000000 29.8850575 15.5688623 14.9712092 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  5:         521   2.197802  0.7662835  0.3992016  0.3838772 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  6:         521  88.135593 19.9233716 10.3792415  9.9808061 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  7:         521  89.655172  9.9616858  5.1896208  4.9904031 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt;  8:         567   5.660377  1.1494253  0.5988024  0.5291005 &lt;data.table[567x4]&gt;</span>
<span class="co">#&gt;  9:         527   3.125000  0.3831418  0.1996008  0.1897533 &lt;data.table[527x4]&gt;</span>
<span class="co">#&gt; 10:         521   1.020408  0.3831418  0.1996008  0.1919386 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 11:         527   0.000000  0.0000000  0.0000000  0.0000000 &lt;data.table[527x4]&gt;</span>
<span class="co">#&gt; 12:         527   6.666667  0.3831418  0.1996008  0.1897533 &lt;data.table[527x4]&gt;</span>
<span class="co">#&gt; 13:         521  39.285714  4.2145594  2.1956088  2.1113244 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 14:         521   1.449275  0.3831418  0.1996008  0.1919386 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 15:         521 100.000000 22.6053640 11.7764471 11.3243762 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 16:         521   3.030303  0.3831418  0.1996008  0.1919386 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 17:         521   0.000000  0.0000000  0.0000000  0.0000000 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 18:         521  79.166667 14.5593870  7.5848303  7.2936660 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 19:         521  81.395349 13.4099617  6.9860279  6.7178503 &lt;data.table[521x4]&gt;</span>
<span class="co">#&gt; 20:         527   0.000000  0.0000000  0.0000000  0.0000000 &lt;data.table[527x4]&gt;</span>
<span class="co">#&gt; 21:         547   3.703704  0.6329114  0.3992016  0.3656307 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 22:         547   2.631579  0.9493671  0.5988024  0.5484461 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 23:         547   3.370787  0.9493671  0.5988024  0.5484461 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 24:         547   5.128205  1.2658228  0.7984032  0.7312614 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 25:         547 100.000000 28.7974684 18.1636727 16.6361974 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 26:         554   5.084746  0.9493671  0.5988024  0.5415162 &lt;data.table[554x4]&gt;</span>
<span class="co">#&gt; 27:         550   6.896552  0.6329114  0.3992016  0.3636364 &lt;data.table[550x4]&gt;</span>
<span class="co">#&gt; 28:         547  13.207547  2.2151899  1.3972056  1.2797075 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 29:         547  81.250000  8.2278481  5.1896208  4.7531993 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 30:         547 100.000000 31.0126582 19.5608782 17.9159049 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 31:         547  66.666667  3.7974684  2.3952096  2.1937843 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 32:         547  60.000000  2.8481013  1.7964072  1.6453382 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 33:         564   3.571429  0.3164557  0.1996008  0.1773050 &lt;data.table[564x4]&gt;</span>
<span class="co">#&gt; 34:         547 100.000000 21.8354430 13.7724551 12.6142596 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 35:         547   3.389831  0.6329114  0.3992016  0.3656307 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 36:         547 100.000000 10.4430380  6.5868263  6.0329068 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 37:         547 100.000000 12.6582278  7.9840319  7.3126143 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 38:         557   6.250000  0.9493671  0.5988024  0.5385996 &lt;data.table[557x4]&gt;</span>
<span class="co">#&gt; 39:         555   4.651163  0.6329114  0.3992016  0.3603604 &lt;data.table[555x4]&gt;</span>
<span class="co">#&gt; 40:         547  75.000000  5.6962025  3.5928144  3.2906764 &lt;data.table[547x4]&gt;</span>
<span class="co">#&gt; 41:         365  50.000000 10.3448276 11.8942731  7.3972603 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 42:         365  40.350877 17.6245211 20.2643172 12.6027397 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 43:         365  43.820225 14.9425287 17.1806167 10.6849315 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 44:         365  52.564103 15.7088123 18.0616740 11.2328767 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 45:         446   2.197802  0.7662835  0.8810573  0.4484305 &lt;data.table[446x4]&gt;</span>
<span class="co">#&gt; 46:         365 100.000000 22.6053640 25.9911894 16.1643836 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 47:         365 100.000000 11.1111111 12.7753304  7.9452055 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 48:         365   5.660377  1.1494253  1.3215859  0.8219178 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 49:         365   3.125000  0.3831418  0.4405286  0.2739726 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 50:         432   1.020408  0.3831418  0.4405286  0.2314815 &lt;data.table[432x4]&gt;</span>
<span class="co">#&gt; 51:         365   0.000000  0.0000000  0.0000000  0.0000000 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 52:         365   6.666667  0.3831418  0.4405286  0.2739726 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 53:         365 100.000000 10.7279693 12.3348018  7.6712329 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 54:         408   1.449275  0.3831418  0.4405286  0.2450980 &lt;data.table[408x4]&gt;</span>
<span class="co">#&gt; 55:         365  62.711864 14.1762452 16.2995595 10.1369863 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 56:         386   3.030303  0.3831418  0.4405286  0.2590674 &lt;data.table[386x4]&gt;</span>
<span class="co">#&gt; 57:         398   0.000000  0.0000000  0.0000000  0.0000000 &lt;data.table[398x4]&gt;</span>
<span class="co">#&gt; 58:         365 100.000000 18.3908046 21.1453744 13.1506849 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 59:         365 100.000000 16.4750958 18.9427313 11.7808219 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 60:         365   0.000000  0.0000000  0.0000000  0.0000000 &lt;data.table[365x4]&gt;</span>
<span class="co">#&gt; 61:         456   3.703704  0.6329114  0.8810573  0.4385965 &lt;data.table[456x4]&gt;</span>
<span class="co">#&gt; 62:         497   2.631579  0.9493671  1.3215859  0.6036217 &lt;data.table[497x4]&gt;</span>
<span class="co">#&gt; 63:         479   3.370787  0.9493671  1.3215859  0.6263048 &lt;data.table[479x4]&gt;</span>
<span class="co">#&gt; 64:         466   5.128205  1.2658228  1.7621145  0.8583691 &lt;data.table[466x4]&gt;</span>
<span class="co">#&gt; 65:         429  10.989011  3.1645570  4.4052863  2.3310023 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 66:         429   5.084746  0.9493671  1.3215859  0.6993007 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 67:         429   6.896552  0.6329114  0.8810573  0.4662005 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 68:         429 100.000000 16.7721519 23.3480176 12.3543124 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 69:         429 100.000000 10.1265823 14.0969163  7.4592075 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 70:         429  31.632653  9.8101266 13.6563877  7.2261072 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 71:         429 100.000000  5.6962025  7.9295154  4.1958042 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 72:         429 100.000000  4.7468354  6.6079295  3.4965035 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 73:         429   3.571429  0.3164557  0.4405286  0.2331002 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 74:         429  37.681159  8.2278481 11.4537445  6.0606061 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 75:         451   3.389831  0.6329114  0.8810573  0.4434590 &lt;data.table[451x4]&gt;</span>
<span class="co">#&gt; 76:         429  36.363636  3.7974684  5.2863436  2.7972028 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 77:         429  17.500000  2.2151899  3.0837004  1.6317016 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 78:         429   6.250000  0.9493671  1.3215859  0.6993007 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 79:         429   4.651163  0.6329114  0.8810573  0.4662005 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt; 80:         429 100.000000  7.5949367 10.5726872  5.5944056 &lt;data.table[429x4]&gt;</span>
<span class="co">#&gt;     count_union      on_g1      on_g2      on_g3   on_union      truth_tbl_venn</span></code></pre></div>
<p>The argument <code>table_for_venn = TRUE</code> will add a new column <code>truth_tbl_venn</code> that contains corresponding truth tables for each row.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sharing_plots1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/sharing_venn.html">sharing_venn</a></span><span class="op">(</span><span class="va">sharing_5</span>, row_range <span class="op">=</span> <span class="fl">1</span>, euler <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">sharing_plots2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/sharing_venn.html">sharing_venn</a></span><span class="op">(</span><span class="va">sharing_5</span>, row_range <span class="op">=</span> <span class="fl">1</span>, euler <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<p>Say that we’re interested in plotting just the first row of our sharing data frame. Then we can call the function <code>sharing_venn</code> and specify in the <code>row_range</code> argument the index 1. Note that this function requires the package <em><a href="https://CRAN.R-project.org/package=eulerr">eulerr</a></em> to work. The argument <code>euler</code> indicates if the function should produce euler or venn diagrams instead.</p>
<p>Once obtained the lists of euler/venn objects we can plot them by simply calling the function <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>:</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sharing_plots1</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<p><img src="sharing_analyses_files/figure-html/unnamed-chunk-17-1.png" width="700"></p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sharing_plots2</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<p><img src="sharing_analyses_files/figure-html/unnamed-chunk-17-2.png" width="700"></p>
<p>There are several options that can be set, for this please refer to <a href="https://jolars.github.io/eulerr/reference/plot.euler.html">eulerr docs</a>.</p>
</div>
<div id="reproducibility" class="section level1">
<h1 class="hasAnchor">
<a href="#reproducibility" class="anchor"></a>Reproducibility</h1>
<p><code>R</code> session information.</p>
<pre><code>#&gt; ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
#&gt;  setting  value                       
#&gt;  version  R version 4.1.1 (2021-08-10)
#&gt;  os       macOS Catalina 10.15.7      
#&gt;  system   x86_64, darwin17.0          
#&gt;  ui       X11                         
#&gt;  language (EN)                        
#&gt;  collate  en_US.UTF-8                 
#&gt;  ctype    en_US.UTF-8                 
#&gt;  tz       UTC                         
#&gt;  date     2021-09-21                  
#&gt; 
#&gt; ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
#&gt;  package      * version date       lib source        
#&gt;  BiocManager    1.30.16 2021-06-15 [1] CRAN (R 4.1.0)
#&gt;  BiocParallel   1.26.2  2021-08-22 [1] Bioconductor  
#&gt;  BiocStyle    * 2.20.2  2021-06-17 [1] Bioconductor  
#&gt;  bookdown       0.24    2021-09-02 [1] CRAN (R 4.1.0)
#&gt;  bslib          0.3.0   2021-09-02 [1] CRAN (R 4.1.0)
#&gt;  cachem         1.0.6   2021-08-19 [1] CRAN (R 4.1.0)
#&gt;  cli            3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
#&gt;  colorspace     2.0-2   2021-06-24 [1] CRAN (R 4.1.0)
#&gt;  crayon         1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
#&gt;  crosstalk      1.1.1   2021-01-12 [1] CRAN (R 4.1.0)
#&gt;  data.table     1.14.0  2021-02-21 [1] CRAN (R 4.1.0)
#&gt;  desc           1.3.0   2021-03-05 [1] CRAN (R 4.1.0)
#&gt;  digest         0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
#&gt;  dplyr          1.0.7   2021-06-18 [1] CRAN (R 4.1.0)
#&gt;  DT             0.19    2021-09-02 [1] CRAN (R 4.1.0)
#&gt;  ellipsis       0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
#&gt;  eulerr         6.1.1   2021-09-06 [1] CRAN (R 4.1.0)
#&gt;  evaluate       0.14    2019-05-28 [1] CRAN (R 4.1.0)
#&gt;  fansi          0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
#&gt;  farver         2.1.0   2021-02-28 [1] CRAN (R 4.1.0)
#&gt;  fastmap        1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
#&gt;  fs             1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
#&gt;  generics       0.1.0   2020-10-31 [1] CRAN (R 4.1.0)
#&gt;  ggplot2        3.3.5   2021-06-25 [1] CRAN (R 4.1.0)
#&gt;  ggrepel        0.9.1   2021-01-15 [1] CRAN (R 4.1.0)
#&gt;  glue           1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
#&gt;  gtable         0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
#&gt;  gtools         3.9.2   2021-06-06 [1] CRAN (R 4.1.0)
#&gt;  highr          0.9     2021-04-16 [1] CRAN (R 4.1.0)
#&gt;  hms            1.1.0   2021-05-17 [1] CRAN (R 4.1.0)
#&gt;  htmltools      0.5.2   2021-08-25 [1] CRAN (R 4.1.0)
#&gt;  htmlwidgets    1.5.4   2021-09-08 [1] CRAN (R 4.1.0)
#&gt;  httr           1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
#&gt;  ISAnalytics  * 1.3.5   2021-09-21 [1] Bioconductor  
#&gt;  jquerylib      0.1.4   2021-04-26 [1] CRAN (R 4.1.0)
#&gt;  jsonlite       1.7.2   2020-12-09 [1] CRAN (R 4.1.0)
#&gt;  knitr          1.34    2021-09-09 [1] CRAN (R 4.1.0)
#&gt;  lifecycle      1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
#&gt;  lubridate      1.7.10  2021-02-26 [1] CRAN (R 4.1.0)
#&gt;  magrittr     * 2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
#&gt;  memoise        2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
#&gt;  munsell        0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
#&gt;  pillar         1.6.2   2021-07-29 [1] CRAN (R 4.1.0)
#&gt;  pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
#&gt;  pkgdown        1.6.1   2020-09-12 [1] CRAN (R 4.1.0)
#&gt;  plyr           1.8.6   2020-03-03 [1] CRAN (R 4.1.0)
#&gt;  polyclip       1.10-0  2019-03-14 [1] CRAN (R 4.1.0)
#&gt;  polylabelr     0.2.0   2020-04-19 [1] CRAN (R 4.1.0)
#&gt;  purrr          0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
#&gt;  R6             2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
#&gt;  ragg           1.1.3   2021-06-09 [1] CRAN (R 4.1.0)
#&gt;  Rcapture       1.4-3   2019-12-16 [1] CRAN (R 4.1.0)
#&gt;  Rcpp           1.0.7   2021-07-07 [1] CRAN (R 4.1.0)
#&gt;  readr          2.0.1   2021-08-10 [1] CRAN (R 4.1.0)
#&gt;  RefManageR   * 1.3.0   2020-11-13 [1] CRAN (R 4.1.0)
#&gt;  rlang          0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
#&gt;  rmarkdown      2.11    2021-09-14 [1] CRAN (R 4.1.0)
#&gt;  rprojroot      2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
#&gt;  sass           0.4.0   2021-05-12 [1] CRAN (R 4.1.0)
#&gt;  scales         1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
#&gt;  sessioninfo  * 1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
#&gt;  stringi        1.7.4   2021-08-25 [1] CRAN (R 4.1.0)
#&gt;  stringr        1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
#&gt;  systemfonts    1.0.2   2021-05-11 [1] CRAN (R 4.1.0)
#&gt;  textshaping    0.3.5   2021-06-09 [1] CRAN (R 4.1.0)
#&gt;  tibble         3.1.4   2021-08-25 [1] CRAN (R 4.1.0)
#&gt;  tidyr          1.1.3   2021-03-03 [1] CRAN (R 4.1.0)
#&gt;  tidyselect     1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
#&gt;  tzdb           0.1.2   2021-07-20 [1] CRAN (R 4.1.0)
#&gt;  utf8           1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
#&gt;  vctrs          0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
#&gt;  withr          2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
#&gt;  xfun           0.26    2021-09-14 [1] CRAN (R 4.1.0)
#&gt;  xml2           1.3.2   2020-04-23 [1] CRAN (R 4.1.0)
#&gt;  yaml           2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
#&gt;  zip            2.2.0   2021-05-31 [1] CRAN (R 4.1.0)
#&gt; 
#&gt; [1] /Users/runner/work/_temp/Library
#&gt; [2] /Library/Frameworks/R.framework/Versions/4.1/Resources/library</code></pre>
</div>
<div id="bibliography" class="section level1">
<h1 class="hasAnchor">
<a href="#bibliography" class="anchor"></a>Bibliography</h1>
<p>This vignette was generated using <em><a href="https://bioconductor.org/packages/3.13/BiocStyle">BiocStyle</a></em> (Oleś, 2021) with <em><a href="https://CRAN.R-project.org/package=knitr">knitr</a></em> (Xie, 2021) and <em><a href="https://CRAN.R-project.org/package=rmarkdown">rmarkdown</a></em> (Allaire, Xie, McPherson, Luraschi, Ushey, Atkins, Wickham, Cheng, Chang, and Iannone, 2021) running behind the scenes.</p>
<p>Citations made with <em><a href="https://CRAN.R-project.org/package=RefManageR">RefManageR</a></em> (McLean, 2017).</p>
<p>
<a id="bib-allaire2021rmarkdown"></a><a href="#cite-allaire2021rmarkdown">[1]</a><cite> J. Allaire, Y. Xie, J. McPherson, et al. <em>rmarkdown: Dynamic Documents for R</em>. R package version 2.11. 2021. URL: <a href="https://github.com/rstudio/rmarkdown">https://github.com/rstudio/rmarkdown</a>.</cite>
</p>
<p>
<a id="bib-mclean2017refmanager"></a><a href="#cite-mclean2017refmanager">[2]</a><cite> M. W. McLean. “RefManageR: Import and Manage BibTeX and BibLaTeX References in R”. In: <em>The Journal of Open Source Software</em> (2017). DOI: <a href="https://doi.org/10.21105/joss.00338">10.21105/joss.00338</a>.</cite>
</p>
<p>
<a id="bib-ole2021biocstyle"></a><a href="#cite-ole2021biocstyle">[3]</a><cite> A. Oleś. <em>BiocStyle: Standard styles for vignettes and other Bioconductor documents</em>. R package version 2.20.2. 2021. URL: <a href="https://github.com/Bioconductor/BiocStyle">https://github.com/Bioconductor/BiocStyle</a>.</cite>
</p>
<p>
<a id="bib-xie2021knitr"></a><a href="#cite-xie2021knitr">[4]</a><cite> Y. Xie. <em>knitr: A General-Purpose Package for Dynamic Report Generation in R</em>. R package version 1.34. 2021. URL: <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>.</cite>
</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Andrea Calabria, Giulio Spinozzi, Giulia Pais.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
